### ISSUE TITLE
subgraphs are not valid/composable?

### ISSUE THREAD

**Issue by michael-groble** [apollographql/apollo-federation-subgraph-compatibility#634]
I'm wondering if I have the wrong impression.  I was expecting the subgraphs to be valid/composable, but instead I get an error (with router v1.52.0):

```
apollo-federation-cli validate implementations/apollo-server/products.graphql packages/subgraphs/inventory/inventory.graphql packages/subgraphs/users/users.graphql 
thread 'main' panicked at apollo-federation/cli/src/main.rs:115:76:
called `Result::unwrap()` on an `Err` value: Error: union member `Inventory` must be an object type
    ╭─[inventory:31:11]
    │
 31 │ interface Inventory @key(fields: "id") {
    │           ────┬────  
    │               ╰────── this is an interface type
    │ 
    │ Help: Union members must be object types.
────╯
```

**Comment by dariuszkuc** [comment]
Can you provide a link to a repository that reproduces the issue? What is your supergraph config? How are you running it?

i.e. running following from this project root directory seems to be fine?
```
make setup
make test subgraph=apollo-server
```

**Comment by michael-groble** [comment]
this repository, apollo-federation-subgraph-compatibility.  After cloning the repo, I run this command from the command line with the router v1.52.0 cli tool
```
apollo-federation-cli validate implementations/apollo-server/products.graphql packages/subgraphs/inventory/inventory.graphql packages/subgraphs/users/users.graphql
```

**Comment by dariuszkuc** [comment]
👋 Subgraphs are correct. `apollo-federation-cli` is currently in alpha/beta and is not something that should be used outside of internal development. [rover](https://www.apollographql.com/docs/rover/) is our official tooling and should be used instead (and this repo relies on it as well).

Create following `supergraph-config.yaml` (assumes it is placed at the root dir of this project, if using different location modify paths accordingly)

```yaml
federation_version: =2.7.8
subgraphs:
  inventory:
    routing_url: http://inventory:4003
    schema:
      file: packages/compatibility/dist/subgraphs/inventory/inventory.graphql
  users:
    routing_url: http://users:4002
    schema:
      file: packages/compatibility/dist/subgraphs/users/users.graphql
  products:
    routing_url: http://products:4001
    schema:
      file: implementations/_template_library_/products.graphql
```

run rover to generate supergraph

```
rover supergraph compose --config=supergraph-config.yaml
```
